export { default as AdminLoginPage } from './AdminLoginPage'
export { default as DashboardPage } from './DashboardPage'
export { default as AdminProductsPage } from './AdminProductsPage'
export { default as AdminOrdersPage } from './AdminOrdersPage'
export { default as AdminVendorsPage } from './AdminVendorsPage'